version: '3'

services:
  snark:
    build: .
    ports:
      - "8081:8080"
    expose:
      - 8081
    volumes:
      - storage:/app/rundata
    secrets:
      - credentials.json
volumes:
  storage:

secrets:
  credentials.json:
    file: ./credentials.json